openapi: 3.0.0
info:
  title: PipelinePlugin
  version: v1
servers:
  - url: https://cloudpipeline-ext.ap-southeast-3.myhuaweicloud.com
    description: Production server
tags:
  - name: PipelinePlugin
security:
  - AuthToken: []
paths:
  /v1/{domain_id}/relation/plugins:
    post:
      tags:
        - PipelinePlugin
      description: >
         Query the CodeArts Pipeline plugins marketplace to discover available tools 
         that can be used as steps within a pipeline.
         These plugins represent reusable tasks such as codecheck, build, test, or deploy,
         and can be inserted into pipeline definitions to automate CI/CD workflows.
      operationId: queryCodeArtsPipelinePluginsList
      parameters:
        - name: domain_id
          in: path
          required: true
          schema:
            type: string
          description: Domain ID of the user, ^[a-f0-9]{32}$
        - name: offset
          in: query
          required: true
          schema:
            type: integer
            default: 0
          description: Offset.
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            default: 100
          description: Size.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListPluginsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/RelationPlugins'

  /v1/{domain_id}/agent-plugin/plugin-input:
    post:
      tags:
        - PipelinePlugin
      description: >
        Retrieve the input configuration schema and usage instructions for a specific 
        CodeArts Pipeline plugin. This should be called whenever a plugin (tool/action) 
        is added to a pipeline, to ensure correct parameter values, required fields, 
        and proper usage. Use this to validate or generate the plugin's input in a pipeline definition.
      operationId: queryCodeArtsPipelinePluginUsageGuide
      parameters:
        - name: X-Language
          in: header
          description: Preferred language of the response
          schema:
            type: string
            default: en-us
            enum: [en-us, zh-cn]
            example: en-us
          required: true
        - name: domain_id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PluginPartQueryDTO'
      responses:
        '200':
          description: List of Plugin input configurations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PluginPartQueryVOListAgentPluginInputVO'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'

components:
  securitySchemes:
    AuthToken:
      type: apiKey
      name: x-auth-token
      in: header
      description: User authentication token required for API access
  schemas:
    RelationPlugins:
      type: object
      properties:
        offset:
          type: integer
          description: Offset.
        limit:
          type: integer
          description: Size.
        total:
          type: integer
          description: Total number.
        data:
          $ref: '#/components/schemas/Data'

    Data:
      type: object
      properties:
        business_type:
          type: string
          description: Service type.
        display_name:
          type: string
          description: Display name.
        unique_id:
          type: string
          description: Unique ID.
        editable:
          type: boolean
          description: Editable.
        removable:
          type: boolean
          description: Removable.
        cloneable:
          type: boolean
          description: Replicable.
        disabled:
          type: boolean
          description: Disabled.
        conditions:
          type: array
          items:
            type: string
          description: Conditions.
        plugins_list:
          type: array
          items:
            $ref: '#/components/schemas/PluginsList'
          description: Plugin list.

    PluginsList:
      type: object
      properties:
        unique_id:
          type: string
          description: Unique ID.
        display_name:
          type: string
          description: Display name.
        plugin_name:
          type: string
          description: Plugin name.
        disabled:
          type: boolean
          description: Disabled.
        group_name:
          type: string
          nullable: true
          description: Group name.
        group_type:
          type: string
          nullable: true
          description: Group type.
        plugin_attribution:
          type: string
          description: Attribute.
        plugin_composition_type:
          type: string
          description: Combination plugin.
        runtime_attribution:
          type: string
          description: Runtime attributes.
        all_steps:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/AllSteps'
          description: Basic plugin list.
        description:
          type: string
          description: Description.
        version_attribution:
          type: string
          description: Version attribute.
        icon_url:
          type: string
          description: Icon URL.
        multi_step_editable:
          type: integer
          description: Editable.
        location:
          type: string
          description: Address.
        publisher_unique_id:
          type: string
          nullable: true
          description: Publisher ID.
        manifest_version:
          type: string
          description: Version.

    AllSteps:
      type: object
      properties:
        plugin_name:
          type: string
          description: Plugin name.
        display_name:
          type: string
          description: Display name.
        version:
          type: string
          description: Version.

    Error400:
      type: object
      properties:
        error_msg:
          type: string
          description: Error message.
        error_code:
          type: string
          description: Error code.

    ListPluginsRequest:
      type: object
      required: 
        - use_condition
        - input_repo_type
        - input_source_type
        - business_type
        - regex_name
      properties:
        use_condition:
          type: string
          description: use "pipeline"
        input_repo_type:
          type: string
          description: Source code repository type, CodeArts Repo, GitLab, or GitHub.
          example: codehub
        input_source_type:
          type: string
          description: use "single"
        business_type:
          type: string
          enum: [Normal, Build,Deploy,Test,Gate,'']
          description: use "", or business_type to filter plugins by category and use case
        regex_name:
          type: string
          description: use "", or single keyword without spaces


    PluginPartQueryDTO:
      type: object
      properties:
        plugin_name:
          type: string
          description: plugin unique identifier, must be data.plugins_list.plugin_name  retrieved by using tool queryPluginsList
        display_name:
          type: string
          description: the plugin display name 
          default: ""
        plugin_attribution:
          type: string
          description: Plugin attribute. The value can be custom or official.  must be retrieved by using tool queryPluginsList 
          default: ""
        version_attribution:
          type: string
          description: Version attribute. The value can be draft or formal. 
          default: ""
      required:
        - plugin_name
        - display_name
        - plugin_attribution
        

    PluginPartQueryVOListAgentPluginInputVO:
      type: object
      properties:
        plugin_name:
          type: string
          description: Plugin name.
        display_name:
          type: string
          description: Display name.
        data:
          type: array
          items:
            $ref: '#/components/schemas/PluginInputData'
          description: Result set.

    PluginInputData:
      type: object
      properties:
        unique_id:
          type: string
          description: Unique ID.
        name:
          type: string
          description: Name.
        default_value:
          type: string
          description: Default value.
        plugin_name:
          type: string
          description: Plugin name.
        version:
          type: string
          description: Version.
        type:
          type: string
          description: Type.
        workspace_id:
          type: string
          description: Tenant ID.
        validation:
          $ref: '#/components/schemas/PluginValidation'
        layout_content:
          type: string
          description: Style information.
        front_data_prop:
          type: string
          nullable: true
          description: Front data property.
        label:
          type: string
          description: Label.
        description:
          type: string
          description: The user enters the shell command here.
        required:
          type: string
          description: Whether required.
        extend_prop:
          type: object
          description: Extended properties.

    PluginValidation:
      type: object
      properties:
        required_message:
          type: string
          description: Message.
        regex:
          type: string
          description: Regex.
        regex_message:
          type: string
          description: Regular expression message.
        max_length:
          type: integer
          description: Maximum length.
        min_length:
          type: integer
          description: Minimum length.