openapi: 3.0.0
info:
  description: Endpoint Management API
  version: v1
  title: ServiceConnectionEndpoints
servers:
  - url: https://cloudpipeline-ext.ap-southeast-3.myhuaweicloud.com
    description: Production server
security:
  - AuthToken: []
paths:
  /v1/serviceconnection/endpoints:
    get:
      description: >
        List all service endpoints for a projet in CodeArts.
        Service endpoints provide links to third-party services to extend your DevOps experience through CodeArts.
        For example, a service endpoint can link you to a Git repository on GitHub to obtain source code,
        to Jenkins to complete certain tasks, or to a Kubernetes cluster to deploy containerized applications.
      tags:
        - Endpoint Management
      operationId: listServiceEndpoints
      parameters:
        - name: project_uuid
          in: query
          description: same as project id, this is required
          required: true
          schema:
            type: string
        - name: region_name
          in: query
          required: true
          schema:
            type: string
          description: use ap-southeast-3, this is required
        - name: module_id
          in: query
          required: false
          schema:
            type: string
          description: Module ID
        - name: offset
          in: query
          required: false
          schema:
            type: integer
          description: Page number
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Number of records per page
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListServiceEndpointsResponse'

components:
  securitySchemes:
    AuthToken:
      type: apiKey
      name: x-auth-token
      in: header
      description: User authentication token required for API access
  schemas:
    ListServiceEndpointsResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code
            message:
              type: string
              description: Error Information
        result:
          type: object
          properties:
            endpoints:
              type: array
              items:
                type: object
                properties:
                  created_by:
                    type: object
                    properties:
                      user_id:
                        type: string
                        description: User ID
                      username:
                        type: string
                        description: Username
                  data:
                    type: object
                    description: Endpoint data
                  module_id:
                    type: string
                    description: Module ID
                  name:
                    type: string
                    description: Module name (for search)
                  project_uuid:
                    type: string
                    description: Project UUID
                  region_name:
                    type: string
                    description: Region name
                  url:
                    type: string
                    description: URL
                  uuid:
                    type: string
                    description: Endpoint ID
            total:
              type: integer
              description: Quantity
        status:
          type: string
          description: Status value
